
package venuefiscalapp;

import javax.swing.JOptionPane;
import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import Io.strategy.ConsoleAndFileOutput;
import Io.strategy.ConsoleOutput;
import Io.strategy.FileOutput;
import Io.strategy.GuiAndFileOutput;
import Io.strategy.GuiOutput;
import Io.strategy.OutputStrategy;

/**
 *
 * MainWindow gui that handles all input and output of data, messages,
 * and exceptions. Can not be run on its own, must be run with GUI
 * 
 * @author Andrew Gunn | amgunn1@hotmail.com
 */
public class MainWindow extends javax.swing.JFrame {
    
    
    //Global Scope fields
    
    final String GDI = "GDI | Venue-Fiscal-App v1.1";
    
    //Dependency Injection
    AbstractApplicationContext context = 
            new ClassPathXmlApplicationContext(new String[] {"startupConfig.xml"});
    //Tech devices
    TechDeviceStrategy device = (Terminal)context.getBean("device");

    //Output Devices
    OutputStrategy guiOutput = (GuiOutput)context.getBean("guiOutput");
    OutputStrategy consoleOutput = (ConsoleOutput)context.getBean("consoleOutput");
    OutputStrategy fileOutput = (FileOutput)context.getBean("fileOutput");
    OutputStrategy guiAndFileOutput = (GuiAndFileOutput)context.getBean("guiAndFileOutput");
    OutputStrategy consoleAndFileOutput = (ConsoleAndFileOutput)context.getBean("consoleAndFileOutput");

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setBounds(600, 300, 410, 330); //Setting positions
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAttendance = new javax.swing.JTextField();
        btnGetTotals = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("GDI | Venue-Fiscal-App v1.1"));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSubmit.setText("Submit Game");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Venue Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Attendance:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnGetTotals.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGetTotals.setText("Get Totals");
        btnGetTotals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTotalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(txtName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(btnGetTotals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnGetTotals, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
                
    
        try {
        
        String n = txtName.getText();
        String a = txtAttendance.getText();
        double attendance = Double.valueOf(a);
        String name = n.toUpperCase();
        
        device.startCalc();
        device.inputInfo(name, attendance);
        device.outputGame(guiOutput);
        
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, nfe.getMessage(), GDI, JOptionPane.ERROR_MESSAGE);

        } catch (IllegalArgumentException iae){
            JOptionPane.showMessageDialog(this, iae.getMessage(), GDI, JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), GDI, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnGetTotalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTotalsActionPerformed
        // TODO add your handling code here:
        
        try {
        
        device.outputTotals(guiOutput);
        
        } catch (IllegalArgumentException iae){
            JOptionPane.showMessageDialog(this, iae.getMessage(), GDI, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), GDI, JOptionPane.ERROR_MESSAGE);
        }
                
        
        
    }//GEN-LAST:event_btnGetTotalsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetTotals;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAttendance;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
